GrTechRK.WebApp/Controllers/CompanyController.cs
using GrTechRK.BSL.Interfaces;
using GrTechRK.Database.Models;
using GrTechRK.DTO;
using GrTechRK.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace GrTechRK.WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    [Route("company")]
    public class CompanyController : BaseController
    {
        private readonly ICompanyService _companyService;

        public CompanyController(
            ICompanyService companyService
        )
        {
            _companyService = companyService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> DetailAsync(int id)
        {
            CompanyDto company = await _companyService.GetAsync(id, CancellationToken.None).ConfigureAwait(false);
            return ViewComponent("CompanyDetail", company);
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> FormAsync(int? id, CancellationToken cancellationToken)
        {
            if (id.HasValue)
            {
                CompanyDto company = await _companyService.GetAsync(id.Value, cancellationToken).ConfigureAwait(false);
                CompanyFormViewModel model = new CompanyFormViewModel()
                {
                    Id = company.Id,
                    Name = company.Name,
                    Email = company.Email,
                    Logo = null,
                    Website = company.Website
                };
                return PartialView("_CompanyFormPopupPartial", model);
            }
            else
            {
                return PartialView("_CompanyFormPopupPartial", null);
            }
        }

        [HttpGet("[action]")]
        public async Task<JsonResult> ListAsync(
            [FromQuery(Name = "draw")] int? draw,
            [FromQuery(Name = "start")] int? start,
            [FromQuery(Name = "length")] int? length,
            [FromQuery(Name = "search[value]")] string search,
            [FromQuery(Name = "order[0][dir]")] string sortDir,
            CancellationToken cancellationToken
        )
        {
            try
            {
                int pageSize = length ?? 10;
                int skip = start ?? length ?? 10;
                int recordsTotal = 0;
                int recordsFiltered = 0;
                string sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                IEnumerable<CompanyDto> companies = await _companyService.GetAllCompaniesAsync(cancellationToken).ConfigureAwait(false);

                recordsTotal = companies.Count();
                if (!string.IsNullOrWhiteSpace(search))
                {
                    companies = companies.Where(e => e.Name.Contains(search) || e.Email.Contains(search) ||
                        e.Website.Contains(search));
                }

                recordsFiltered = companies.Count();
                if (!string.IsNullOrWhiteSpace(sortColumn) && !string.IsNullOrWhiteSpace(sortDir))
                {
                    string sort = $"{sortColumn} {sortDir}";
                    companies = sort switch
                    {
                        "name asc" => companies.OrderBy(e => e.Name).Skip(skip).Take(pageSize),
                        "name desc" => companies.OrderByDescending(e => e.Name).Skip(skip).Take(pageSize),
                        "email asc" => companies.OrderBy(e => e.Email).Skip(skip).Take(pageSize),
                        "email desc" => companies.OrderByDescending(e => e.Email).Skip(skip).Take(pageSize),
                        "website asc" => companies.OrderBy(e => e.Website).Skip(skip).Take(pageSize),
                        "website desc" => companies.OrderByDescending(e => e.Website).Skip(skip).Take(pageSize),
                        _ => companies.OrderBy(e => e.Name).Skip(skip).Take(pageSize),
                    };
                }

                return Json(new { draw, recordsTotal, recordsFiltered, data = companies });
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost("[action]")]
        public async Task<DtoResponse> AddAsync(CompanyFormViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using MemoryStream ms = new MemoryStream();
                    if (model.Logo != null)
                    {
                        model.Logo.CopyTo(ms);
                    }

                    Company company = new Company()
                    {
                        Id = model.Id,
                        Name = model.Name,
                        Email = model.Email,
                        Logo = model.Logo != null ? ms.ToArray() : null,
                        Website = !string.IsNullOrWhiteSpace(model.Website) ? new Uri(model.Website, UriKind.Absolute) : null
                    };

                    return Response_Ok(await _companyService.AddAsync(company).ConfigureAwait(false));
                }
                else
                {
                    return Response_Exception(ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                }
            }
            catch (Exception exc)
            {
                return Response_Exception(exc);
            }
        }

        [HttpPut]
        public async Task<DtoResponse> UpdateAsync(CompanyFormViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Company company = new Company()
                    {
                        Id = model.Id,
                        Name = model.Name,
                        Email = model.Email,
                        Logo = null,
                        Website = !string.IsNullOrWhiteSpace(model.Website) ? new Uri(model.Website, UriKind.Absolute) : null
                    };

                    return Response_Ok(await _companyService.UpdateAsync(company).ConfigureAwait(false));
                }
                else
                {
                    return Response_Exception(ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                }
            }
            catch (Exception exc)
            {
                return Response_Exception(exc);
            }
        }

        [HttpPut("[action]")]
        public async Task<DtoResponse> UploadAsync(CompanyFormViewModel model)
        {
            try
            {
                using MemoryStream ms = new MemoryStream();
                if (model.Logo != null)
                {
                    model.Logo.CopyTo(ms);
                }

                return Response_Ok(await _companyService.UpdateLogoAsync(model.Id.Value, ms.ToArray()).ConfigureAwait(false));
            }
            catch (Exception exc)
            {
                return Response_Exception(exc);
            }
        }

        [HttpDelete]
        public async Task<DtoResponse> DeleteAsync(int id)
        {
            try
            {
                await _companyService.DeleteAsync(id).ConfigureAwait(false);
                return Response_Ok();
            }
            catch (Exception exc)
            {
                return Response_Exception(exc);
            }
        }
    }
}

GrTechRK.WebApp/Controllers/QuoteController.cs
using GrTechRK.BSL.Interfaces;
using GrTechRK.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace GrTechRK.WebApp.Controllers
{
    [AllowAnonymous]
    [Route("daily-quotes")]
    public class QuoteController : BaseController
    {
        private readonly IQuoteService _quoteService;

        public QuoteController(
            IQuoteService quoteService
        )
        {
            _quoteService = quoteService;
        }

        [HttpGet]
        public async Task<IActionResult> IndexAsync(CancellationToken cancellationToken)
        {
            ImmutableHashSet<QuoteDto> quoteDtos = await _quoteService.GetRandomDailyQuotesAsync(cancellationToken).ConfigureAwait(false);
            HttpContext.Session.SetString("_Quotes", JsonSerializer.Serialize(quoteDtos));

            return View();
        }

        [HttpGet("[action]")]
        public async Task RefreshAsync(CancellationToken cancellationToken)
        {
            ImmutableHashSet<QuoteDto> quoteDtos = await _quoteService.GetRandomDailyQuotesAsync(cancellationToken).ConfigureAwait(false);
            HttpContext.Session.SetString("_Quotes", JsonSerializer.Serialize(quoteDtos));
        }

        [HttpGet("daily-quotes")]
        public async Task<JsonResult> DailyQuotesAsync(
            [FromQuery(Name = "draw")] int? draw,
            [FromQuery(Name = "start")] int? start,
            [FromQuery(Name = "length")] int? length,
            [FromQuery(Name = "search[value]")] string search,
            [FromQuery(Name = "order[0][dir]")] string sortDir,
            CancellationToken cancellationToken
        )
        {
            try
            {
                int pageSize = length ?? 10;
                int skip = start ?? length ?? 10;
                int recordsTotal = 0;
                int recordsFiltered = 0;
                string sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                string jsonText = HttpContext.Session.GetString("_Quotes");
                IEnumerable<QuoteDto> quoteDtos;
                if (string.IsNullOrWhiteSpace(jsonText))
                {
                    quoteDtos = await _quoteService.GetRandomDailyQuotesAsync(cancellationToken).ConfigureAwait(false);
                    HttpContext.Session.SetString("_Quotes", JsonSerializer.Serialize(quoteDtos));
                } else
                {
                    quoteDtos = JsonSerializer.Deserialize<IEnumerable<QuoteDto>>(jsonText);
                }

                recordsTotal = recordsFiltered = quoteDtos.Count();
                if (!string.IsNullOrWhiteSpace(sortColumn) && !string.IsNullOrWhiteSpace(sortDir))
                {
                    string sort = $"{sortColumn} {sortDir}";
                    quoteDtos = sort switch
                    {
                        "quote asc" => quoteDtos.OrderBy(e => e.Quote).Skip(skip).Take(pageSize),
                        "quote desc" => quoteDtos.OrderByDescending(e => e.Quote).Skip(skip).Take(pageSize),
                        "author asc" => quoteDtos.OrderBy(e => e.Author).Skip(skip).Take(pageSize),
                        "author desc" => quoteDtos.OrderByDescending(e => e.Author).Skip(skip).Take(pageSize),
                        _ => quoteDtos.OrderBy(e => e.Quote).Skip(skip).Take(pageSize),
                    };
                }

                return Json(new { draw, recordsTotal, recordsFiltered, data = quoteDtos });
            }
            catch (Exception exc)
            {
                throw exc;
            }
        }
    }
}

GrTechRK.WebApp/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - GrTechRK</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="~/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" />
    <!-- Toastr -->
    <link rel="stylesheet" href="~/plugins/toastr/toastr.min.css" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- Custom style -->
    <link rel="stylesheet" href="~/css/site_login.min.css" />
</head>
<body class="hold-transition login-page bg-login">
    @RenderBody()

    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- SweetAlert2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- Custom -->
    <script src="~/js/showMessage.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

GrTechRK.WebApp/Views/Shared/_Footer.cshtml
<div class="text-right">
    <strong>Copyright &copy; @DateTime.Now.Year <a href="@Url.Action("Index", "Home")">GrTech RK</a>.</strong> All rights reserved.
</div>

GrTechRK.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - GrTechRK</title>

    <!-- Favicon -->
    <link rel="icon" href="~/img/icon.png" type="image/png" />
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">
    <!-- Datatable -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" />
    <!-- fullCalendar -->
    <link rel="stylesheet" href="~/plugins/fullcalendar/main.css">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="~/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
    <!-- Toastr -->
    <link rel="stylesheet" href="~/plugins/toastr/toastr.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">

    <!-- Custom -->
    <link rel="stylesheet" href="~/css/site.min.css" />

</head>
<body class="hold-transition sidebar-mini layout-fixed text-sm">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-primary navbar-dark">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item" style="padding-top: 6px;">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                @*<li class="nav-item d-none d-sm-inline-block">
                        <img src="~/img/logo_ptkpi_sm.png" class="img-fluid" style="max-height: 45px;" />
                    </li>*@
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <button type="button" class="btn btn-link nav-link">
                            <i class="fas fa-user"></i>
                            @User.Identity.Name
                        </button>
                    </li>
                    <li class="nav-item">
                        <button type="button" class="btn btn-link nav-link" onclick='signOut()'>
                            <i class="fas fa-lock with-text"></i>
                            Sign Out
                        </button>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" href='@Url.Action("Login", "Home")'>
                            <i class="fas fa-sign-in with-text"></i>
                            Sign In
                        </a>
                    </li>
                }
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <div class="bg-white text-center">
                <img src="~/img/icon.png" class="img-fluid" />
            </div>

            <!-- Brand Logo -->
            <a href='@Url.Action("Index", "Home")' class="brand-link text-center">
                <span class="brand-text font-weight-light text-lg"><strong>GrTech</strong> RK</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <partial name="_SidebarMenu.cshtml" />
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <partial name="_Footer.cshtml" />
        </footer>
    </div>

    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>

    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>

    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>

    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>

    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>

    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>

    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>

    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>

    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>

    <!-- Datatable -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>

    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>

    <!-- SweetAlert2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>

    <!-- fullCalendar 2.2.5 -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/fullcalendar/main.min.js"></script>

    <!-- Bs Custom File Input -->
    <script src="~/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>

    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>

    <!-- Axios -->
    <script src="~/plugins/axios/js/axios.min.js"></script>

    <!-- Custom Script -->
    <script src="~/js/showMessage.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script type="text/javascript">
        let controller = '@Url.Action("Logout", "Home")';

        $(document).ready(function () {
            bsCustomFileInput.init();
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })
        });

        function signOut() {
            $.post(controller)
                .done(function (response) {
                    window.location.href = response;
                });
        }
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

GrTechRK.WebApp/Views/Shared/_SidebarMenu.cshtml
<!-- Sidebar Menu -->
<nav class="mt-2 pb-4">
    <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" style="margin-bottom: 4rem;" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
            <a href="@Url.Action("Index", "Home")" class="nav-link @Html.IsActive("Index", "Home")">
                <i class="fas fa-home nav-icon"></i>
                <p>Home</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("Index", "Quote")" class="nav-link @Html.IsActive("Index", "Quote")">
                <i class="fas fa-comment-dots nav-icon"></i>
                <p>Daily Quotes</p>
            </a>
        </li>
        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
            <li class="nav-item">
                <a href='@Url.Action("Index", "Company")' class="nav-link @Html.IsActive("Index", "Company")">
                    <i class="fas fa-building nav-icon"></i>
                    <p>Company</p>
                </a>
            </li>
            <li class="nav-item">
                <a href='@Url.Action("Index", "Employee")' class="nav-link @Html.IsActive("Index", "Employee")">
                    <i class="fas fa-users nav-icon"></i>
                    <p>Employee</p>
                </a>
            </li>
        }
    </ul>
</nav>
<!-- /.sidebar-menu -->