GrTechRK.WebApp/Controllers/EmployeeController.cs
using GrTechRK.BSL.Interfaces;
using GrTechRK.Database.Models;
using GrTechRK.DTO;
using GrTechRK.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace GrTechRK.WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    [Route("employee")]
    public class EmployeeController : BaseController
    {
        private readonly IEmployeeService _employeeService;

        public EmployeeController(
            IEmployeeService employeeService
        )
        {
            _employeeService = employeeService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> FormAsync(int? id, CancellationToken cancellationToken)
        {
            if (id.HasValue)
            {
                EmployeeDto employee = await _employeeService.GetAsync(id.Value, cancellationToken).ConfigureAwait(false);
                EmployeeFormViewModel model = new EmployeeFormViewModel()
                {
                    Id = employee.Id,
                    FirstName = employee.FirstName,
                    LastName = employee.LastName,
                    CompanyId = employee.CompanyId,
                    Email = employee.Email,
                    Phone = employee.Phone
                };
                return PartialView("_EmployeeFormPopupPartial", model);
            }
            else
            {
                return PartialView("_EmployeeFormPopupPartial", null);
            }
        }

        [HttpGet("[action]")]
        public async Task<JsonResult> ListAsync(
            [FromQuery(Name = "draw")] int? draw,
            [FromQuery(Name = "start")] int? start,
            [FromQuery(Name = "length")] int? length,
            [FromQuery(Name = "search[value]")] string search,
            [FromQuery(Name = "order[0][dir]")] string sortDir,
            [FromQuery(Name = "s")] string startDate,
            [FromQuery(Name = "e")] string endDate,
            [FromQuery(Name = "fn")] string firstName,
            [FromQuery(Name = "ln")] string lastName,
            [FromQuery(Name = "m")] string email,
            [FromQuery(Name = "c")] string companyId,
            CancellationToken cancellationToken
        )
        {
            try
            {
                int pageSize = length ?? 10;
                int skip = start ?? length ?? 10;
                int recordsTotal = 0;
                int recordsFiltered = 0;
                string sortColumn = Request.Query["columns[" + Request.Query["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                IEnumerable<EmployeeDto> employees = await _employeeService.GetAllEmployeesAsync(cancellationToken).ConfigureAwait(false);

                recordsTotal = employees.Count();
                if (!string.IsNullOrWhiteSpace(search))
                {
                    employees = employees.Where(e => e.FirstName.Contains(search) || e.LastName.Contains(search) ||
                        e.CompanyName.Contains(search) || e.Email.Contains(search) || e.Phone.Contains(search));
                }

                if (!string.IsNullOrWhiteSpace(startDate))
                {
                    DateTime sd = DateTime.Parse(startDate);
                    employees = employees.Where(e => e.Created >= sd);
                }
                if (!string.IsNullOrWhiteSpace(endDate))
                {
                    DateTime ed = DateTime.Parse(endDate);
                    employees = employees.Where(e => e.Created <= ed);
                }
                if (!string.IsNullOrWhiteSpace(firstName))
                {
                    employees = employees.Where(e => e.FirstName.Contains(firstName));
                }
                if (!string.IsNullOrWhiteSpace(lastName))
                {
                    employees = employees.Where(e => e.LastName.Contains(lastName));
                }
                if (!string.IsNullOrWhiteSpace(email))
                {
                    employees = employees.Where(e => e.Email.Contains(email));
                }
                if (!string.IsNullOrWhiteSpace(companyId))
                {
                    int.TryParse(companyId, out int cid);
                    employees = employees.Where(e => e.CompanyId == cid || cid == 0);
                }

                recordsFiltered = employees.Count();
                if (!string.IsNullOrWhiteSpace(sortColumn) && !string.IsNullOrWhiteSpace(sortDir))
                {
                    string sort = $"{sortColumn} {sortDir}";
                    employees = sort switch
                    {
                        "fullName asc" => employees.OrderBy(e => e.FullName).Skip(skip).Take(pageSize),
                        "fullName desc" => employees.OrderByDescending(e => e.FullName).Skip(skip).Take(pageSize),
                        "companyName asc" => employees.OrderBy(e => e.CompanyName).Skip(skip).Take(pageSize),
                        "companyName desc" => employees.OrderByDescending(e => e.CompanyName).Skip(skip).Take(pageSize),
                        "email asc" => employees.OrderBy(e => e.Email).Skip(skip).Take(pageSize),
                        "email desc" => employees.OrderByDescending(e => e.Email).Skip(skip).Take(pageSize),
                        "phone asc" => employees.OrderBy(e => e.Phone).Skip(skip).Take(pageSize),
                        "phone desc" => employees.OrderByDescending(e => e.Phone).Skip(skip).Take(pageSize),
                        "created asc" => employees.OrderBy(e => e.Created).Skip(skip).Take(pageSize),
                        "created desc" => employees.OrderByDescending(e => e.Created).Skip(skip).Take(pageSize),
                        _ => employees.OrderBy(e => e.FullName).Skip(skip).Take(pageSize),
                    };
                }

                return Json(new { draw, recordsTotal, recordsFiltered, data = employees });
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost("[action]")]
        public async Task<DtoResponse> AddAsync(EmployeeFormViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Employee employee = new Employee()
                    {
                        Id = model.Id,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        CompanyId = model.CompanyId,
                        Email = model.Email,
                        Phone = model.Phone
                    };

                    return Response_Ok(await _employeeService.AddAsync(employee).ConfigureAwait(false));
                }
                else
                {
                    return Response_Exception(ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                }
            }
            catch (Exception exc)
            {
                return Response_Exception(exc);
            }
        }

        [HttpPut]
        public async Task<DtoResponse> UpdateAsync(EmployeeFormViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Employee employee = new Employee()
                    {
                        Id = model.Id,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        CompanyId = model.CompanyId,
                        Email = model.Email,
                        Phone = model.Phone
                    };

                    return Response_Ok(await _employeeService.UpdateAsync(employee).ConfigureAwait(false));
                }
                else
                {
                    return Response_Exception(ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                }
            }
            catch (Exception exc)
            {
                return Response_Exception(exc);
            }
        }

        [HttpDelete]
        public async Task<DtoResponse> DeleteAsync(int id)
        {
            try
            {
                await _employeeService.DeleteAsync(id).ConfigureAwait(false);
                return Response_Ok();
            }
            catch (Exception exc)
            {
                return Response_Exception(exc);
            }
        }
    }
}

GrTechRK.WebApp/ViewComponents/CompanySelectorViewComponent.cs
using GrTechRK.BSL.Interfaces;
using GrTechRK.DTO;
using GrTechRK.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace GrTechRK.WebApp.ViewComponents
{
    [ViewComponent(Name = "CompanySelector")]
    public class CompanySelectorViewComponent : ViewComponent
    {
		private readonly ICompanyService _companyService;

		public CompanySelectorViewComponent(
			ICompanyService companyService
		)
		{
            _companyService = companyService;
        }

		public async Task<IViewComponentResult> InvokeAsync(string id, string selected)
		{
			ImmutableHashSet<SelectListItem> items = await GetItemsAsync().ConfigureAwait(false);
			SelectorViewModel model = new SelectorViewModel(
				id: id,
				selectedValue: selected,
				data: items
			);
			return View(model);
		}

		private async Task<ImmutableHashSet<SelectListItem>> GetItemsAsync()
		{
			ImmutableHashSet<CompanyDto> results = await _companyService.GetAllCompaniesAsync(CancellationToken.None).ConfigureAwait(false);
			return results.Select(r => new SelectListItem(r.Name, r.Id.ToString())).ToImmutableHashSet();
		}
	}
}

GrTechRK.WebApp/Views/Employee/_EmployeeFormPopupPartial.cshtml
@model EmployeeFormViewModel
@{
    string action = Model is null ? "Add" : "Edit";
}

<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">@action Employee</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>

        <div class="modal-body">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label>First Name</label>
                        <input id="txtFirstName" type="text" class="form-control" placeholder="First Name" value="@(Model?.FirstName)" />
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label>Last Name</label>
                        <input id="txtLastName" type="text" class="form-control" placeholder="Last Name" value="@(Model?.LastName)" />
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label>Company</label>
                        <vc:company-selector id="1" selected="@(Model?.CompanyId)"></vc:company-selector>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label>Email</label>
                        <input id="txtEmail" type="email" class="form-control" placeholder="Email" value="@(Model?.Email)" />
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label>Phone</label>
                        <input id="txtPhone" type="tel" class="form-control" placeholder="Phone" value="@(Model?.Phone)" />
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal">Close</button>
            @if (action == "Add")
            {
                <button type="button" id="btnAction" class="btn btn-primary" onclick="addData()">@action</button>
            }
            else
            {
                <button type="button" id="btnAction" class="btn btn-primary" onclick="editData(@Model.Id)">@action</button>
            }
        </div>
    </div>
</div>